version: '3.1'
services:
  wordpress:
    image: wordpress:php7.2-apache
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./website:/var/www/html
      - ./ssl:/etc/apache2/ssl  # Mount SSL directory
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
